/* liblwjgl_lz4.so for ARM64: the functions of LWJGL's LZ4 binding (JNI exports) that .NET games
 * call directly (Stardew Valley's multiplayer compression), on the system's liblz4. LWJGL's own
 * binding is generated by its Java build; these are its C signatures: JNIEnv and jclass first
 * (unused, .NET passes whatever), pointers as jlong. */
#include <stdint.h>
#include <lz4.h>

#define EXPORT __attribute__((visibility("default")))

EXPORT int32_t Java_org_lwjgl_util_lz4_LZ4_LZ4_1compressBound(void *env, void *cls, int32_t size)
{
    return LZ4_compressBound(size);
}

EXPORT int32_t Java_org_lwjgl_util_lz4_LZ4_nLZ4_1compress_1default(void *env, void *cls, int64_t src,
                                                                   int64_t dst, int32_t srcSize, int32_t dstCapacity)
{
    return LZ4_compress_default((const char *)(intptr_t)src, (char *)(intptr_t)dst, srcSize, dstCapacity);
}

EXPORT int32_t Java_org_lwjgl_util_lz4_LZ4_nLZ4_1decompress_1safe(void *env, void *cls, int64_t src,
                                                                  int64_t dst, int32_t compressedSize, int32_t dstCapacity)
{
    return LZ4_decompress_safe((const char *)(intptr_t)src, (char *)(intptr_t)dst, compressedSize, dstCapacity);
}

EXPORT int32_t Java_org_lwjgl_util_lz4_LZ4_LZ4_1versionNumber(void *env, void *cls)
{
    return LZ4_versionNumber();
}
