#!/usr/bin/python3
"""gen-flat: the flat Steam API functions of Kettle's ARM64 libsteam_api.so (steam_api.c).

names.txt lists them: `forward <name>` for SteamAPI_ISteam<I>_<M> (each becomes a jump to the
virtual method at the offset the game's map gives, kettle_flat_off), `accessor <name>` for
SteamAPI_Steam<I>_v<N> (each calls kettle_accessor with its index). Writes flat.S and
flat_names.h (the names, sorted, for steam_api.c to look up the map's entries by).

  gen-flat.py names.txt <out dir>
"""
import sys

names = {"forward": set(), "accessor": set()}
with open(sys.argv[1], encoding="ascii") as f:
    for line in f:
        line = line.split("#")[0].split()
        if len(line) == 2 and line[0] in names:
            names[line[0]].add(line[1])
fwd = sorted(names["forward"], key=str.encode)
acc = sorted(names["accessor"], key=str.encode)
if len(fwd) >= 4096 or len(acc) >= 4096:
    sys.exit("too many names for the ldr/mov immediates")
out = sys.argv[2]

with open(f"{out}/flat_names.h", "w") as h:
    h.write("// generated by gen-flat.py from names.txt\n")
    h.write(f"#define KETTLE_FLAT_COUNT {len(fwd)}\n#define KETTLE_ACCESSOR_COUNT {len(acc)}\n")
    for var, lst in (("kettle_flat_names", fwd), ("kettle_accessor_names", acc)):
        h.write(f"static const char *const {var}[] = {{\n")
        h.writelines(f'    "{n}",\n' for n in lst)
        h.write("};\n")

with open(f"{out}/flat.S", "w") as s:
    s.write("// generated by gen-flat.py from names.txt: see steam_api.c\n\t.text\n")
    for i, n in enumerate(fwd):
        s.write(f"""
\t.globl {n}
\t.type {n}, %function
\t.p2align 2
{n}:
\tadrp x16, kettle_flat_off
\tadd x16, x16, :lo12:kettle_flat_off
\tldr x16, [x16, #{i * 8}]
\tcbz x16, 1f
\tsub x16, x16, #1
\tldr x17, [x0]
\tldr x17, [x17, x16]
\tbr x17
1:\tmov w0, #{i}
\tb kettle_flat_missing
\t.size {n}, .-{n}
""")
    for i, n in enumerate(acc):
        s.write(f"""
\t.globl {n}
\t.type {n}, %function
\t.p2align 2
{n}:
\tmov w0, #{i}
\tb kettle_accessor
\t.size {n}, .-{n}
""")
    s.write('\n\t.section .note.GNU-stack,"",%progbits\n')
