#!/usr/bin/env python3
"""Render the Kettle Steam startup movie from the SVG art in art/.

Usage: render-startup.py ART_DIR OUT.webm

Same layout as the Plymouth splash (kettle.script), so boot runs splash -> black -> the
same picture building up again: the kettle rises in over a warm glow, steam starts from the
spout and builds to a boil, the name spells out, then everything fades to black and Steam's
UI appears. 1920x1080 (the Portal's screen), 60 fps, VP9 + Opus like Valve's own movies.
Frames are SVG rendered by rsvg-convert; the sound (steam hiss and a two-note chime) is
generated by ffmpeg. Deterministic: the same art gives the same movie.
"""
import concurrent.futures
import math
import os
import random
import re
import subprocess
import sys
import tempfile

W, H, FPS, SECONDS = 1920, 1080, 60, 5.0

# layout, as kettle.script places it at 1920x1080
KETTLE_X, KETTLE_Y, KETTLE_SIZE = 800, 338, 320
SPOUT_X, SPOUT_Y = KETTLE_X + 292, KETTLE_Y + 138      # kettle.svg (234,110) at 320 px
WORD_X, WORD_Y = 794, 694
STEAM_W, STEAM_H = 60, 180                              # steam.svg at 1.25x
STEAM_BASE_X, STEAM_BASE_Y = 30, 170                    # its (24,136) at that size


def ease_out(x):
    x = min(max(x, 0.0), 1.0)
    return 1 - (1 - x) ** 3


def ramp(t, start, length):
    return min(max((t - start) / length, 0.0), 1.0)


def nested(svg, x, y, w, h):
    """An art file as a nested <svg> placed at x,y with size w,h."""
    body = re.sub(r'<svg\b[^>]*?\bwidth="[^"]*"\s+height="[^"]*"', '<svg', svg, count=1)
    return body.replace('<svg', f'<svg x="{x:.2f}" y="{y:.2f}" width="{w:.2f}" height="{h:.2f}"', 1)


def load(art, name):
    with open(os.path.join(art, name)) as f:
        return re.sub(r'<!--.*?-->', '', f.read(), flags=re.S)


def wisps():
    """Steam puffs: (birth time, lifetime, size, sway phase, drift), denser towards the boil."""
    rng = random.Random(1120)
    out, t = [], 0.85
    while t < 4.2:
        out.append((t, rng.uniform(1.3, 1.8), rng.uniform(0.85, 1.35),
                    rng.uniform(0, math.tau), rng.uniform(-6, 30)))
        # every 0.26 s at first, every 0.09 s at the boil
        t += 0.26 - 0.17 * ease_out((t - 0.85) / 1.2)
    return out


def frame(t, art, puffs):
    kettle, steam, word = art["kettle"], art["steam"], art["word"]
    fade_out = 1 - ramp(t, 3.9, 0.8)
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}">',
             '<defs><radialGradient id="glow"><stop offset="0" stop-color="#ff8a3d" stop-opacity="1"/>'
             '<stop offset="1" stop-color="#ff8a3d" stop-opacity="0"/></radialGradient></defs>',
             f'<rect width="{W}" height="{H}" fill="#000"/>',
             f'<g opacity="{fade_out:.4f}">']

    # warm glow behind the kettle: blooms in, then breathes
    glow = 0.16 * ease_out(ramp(t, 0.3, 1.2)) * (1 + 0.15 * math.sin(t * 3.2))
    parts.append(f'<ellipse cx="{KETTLE_X + 160}" cy="{KETTLE_Y + 210}" rx="420" ry="300" '
                 f'fill="url(#glow)" opacity="{glow:.4f}"/>')

    # steam behind the kettle
    for born, life, size, phase, drift in puffs:
        age = (t - born) / life
        if not 0 <= age <= 1:
            continue
        s = size * (1 + 0.6 * age)
        sway = math.sin(age * math.tau + phase) * 11
        x = SPOUT_X - STEAM_BASE_X * s + sway + drift * age
        y = SPOUT_Y - STEAM_BASE_Y * s - age * 170
        a = math.sin(age * math.pi) * 0.6 * min(1, (t - 0.85) / 0.8)
        parts.append(f'<g opacity="{a:.4f}">{nested(steam, x, y, STEAM_W * s, STEAM_H * s)}</g>')

    # kettle: rises in, and rattles a little at the boil
    k = ease_out(ramp(t, 0.3, 0.8))
    boil = math.sin(math.pi * ramp(t, 1.9, 0.6))
    kx = KETTLE_X + math.sin(t * math.tau * 17) * 1.6 * boil
    ky = KETTLE_Y + (1 - k) * 36
    parts.append(f'<g opacity="{k:.4f}">{nested(kettle, kx, ky, KETTLE_SIZE, KETTLE_SIZE)}</g>')

    # the name, letter by letter
    head, letters = word
    parts.append(nested(head, WORD_X, WORD_Y, 332, 48))
    for i, letter in enumerate(letters):
        a = ease_out(ramp(t, 1.45 + 0.07 * i, 0.35))
        parts.append(f'<g opacity="{a:.4f}" transform="translate(0 {(1 - a) * 14:.2f})">{letter}</g>')
    parts.append('</g></svg>')   # the wordmark's stroke group and its <svg>

    parts.append('</g></svg>')   # fade-out group and the frame
    return "".join(parts)


def split_word(svg):
    """wordmark.svg as (its opening up to and including the stroke group, [letter paths])."""
    m = re.search(r'(<svg.*?<g[^>]*>)(.*?)</g>\s*</svg>', svg, re.S)
    letters = re.findall(r'<path[^>]*/>', m.group(2))
    assert len(letters) == 6, "wordmark.svg should have one path per letter"
    return m.group(1), letters


def main():
    art_dir, out = sys.argv[1], sys.argv[2]
    art = {"kettle": load(art_dir, "kettle.svg"), "steam": load(art_dir, "steam.svg"),
           "word": split_word(load(art_dir, "wordmark.svg"))}
    puffs = wisps()
    frames = int(SECONDS * FPS)
    with tempfile.TemporaryDirectory() as tmp:
        def render(n):
            svg = os.path.join(tmp, f"{n:04d}.svg")
            with open(svg, "w") as f:
                f.write(frame(n / FPS, art, puffs))
            subprocess.run(["rsvg-convert", svg, "-o", os.path.join(tmp, f"{n:04d}.png")], check=True)
            os.remove(svg)

        with concurrent.futures.ThreadPoolExecutor(os.cpu_count()) as pool:
            list(pool.map(render, range(frames)))

        # steam hiss swelling to the boil, and a warm chime (E5 + B5) as the name appears
        hiss = ("anoisesrc=color=pink:amplitude=0.5:duration=5:seed=1120,"
                "highpass=f=2500,lowpass=f=9000,"
                "volume='0.22*min(1,max(0,(t-0.8)/1.4))*min(1,max(0,(4.6-t)/1.4))':eval=frame")
        chime = ("aevalsrc='if(gt(t,1.45),(0.20*sin(2*PI*659.25*t)+0.13*sin(2*PI*987.77*t)"
                 "+0.05*sin(2*PI*1318.5*t))*exp(-2.6*(t-1.45)),0)':s=48000:d=5")
        subprocess.run([
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
            "-framerate", str(FPS), "-i", os.path.join(tmp, "%04d.png"),
            "-f", "lavfi", "-i", hiss, "-f", "lavfi", "-i", chime,
            "-filter_complex", "[1:a]aformat=sample_rates=48000:channel_layouts=mono[h];"
                               "[2:a]aformat=channel_layouts=mono[c];"
                               "[h][c]amix=inputs=2:normalize=0,pan=stereo|c0=c0|c1=c0,"
                               "afade=t=out:st=4.4:d=0.6[a]",
            "-map", "0:v", "-map", "[a]",
            "-c:v", "libvpx-vp9", "-pix_fmt", "yuv420p", "-b:v", "0", "-crf", "30",
            "-row-mt", "1", "-deadline", "good", "-cpu-used", "4",
            "-c:a", "libopus", "-b:a", "96k", "-t", str(SECONDS), out], check=True)


if __name__ == "__main__":
    main()
